## H2 ??
spring:
  h2:
    console:
      enabled: true
      path: /h2
## DataSource ??
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:mem:test # ??? DB
    username: sa
    password: 1234

## Hibernate
  jap:
    show-sql: true
    properties:
      hibername:
        format_sql: true